# Generated by Django 3.2 on 2024-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guessnumbers',
            old_name='update_data',
            new_name='update_date',
        ),
    ]
